import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navber/page";
import Footer from "@/components/footer/page";

const geistSans = Poppins({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={geistSans.className}
      >
        <header className="bg-gray-800 text-white">
          <Navbar />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
